#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ODOO_USER WITH PASSWORD '$ODOO_PASS';

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $ODOO_USER;
    ALTER DATABASE $POSTGRES_DB OWNER TO $ODOO_USER;
EOSQL

