#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS hstore;
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE EXTENSION IF NOT EXISTS postgis_raster;
    CREATE EXTENSION IF NOT EXISTS postgis_topology;
    CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
    CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;

    GRANT USAGE ON SCHEMA public TO $ODOO_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $ODOO_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO $ODOO_USER;
EOSQL
